# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlDetikNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(blank=True)),
                ('date', models.CharField(max_length=50)),
                ('main_headline', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
            ],
        ),
    ]
