# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0002_auto_20180320_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawldetiknews',
            name='term',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crawldetiknews',
            name='tf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crawldetiknews',
            name='word',
            field=models.TextField(blank=True),
        ),
    ]
