# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0003_auto_20180326_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawldetiknews',
            old_name='term',
            new_name='count_term',
        ),
        migrations.RenameField(
            model_name='crawldetiknews',
            old_name='word',
            new_name='sum_all_word',
        ),
    ]
