# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0006_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawldetiknews',
            name='kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplikasi.Kelas'),
            preserve_default=False,
        ),
    ]
